site_name: Qlik Core

theme:
  name: 'material'
  logo: 'images/QlikCore-Horizontal-Print-white.svg'
  # feature:
  #   tabs: true
  custom_dir: 'theme'

extra_css:
  - 'stylesheets/custom-style.css'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

repo_name: 'qlik-ea/info'
repo_url: 'https://github.com/qlik-ea/info'
google_analytics: ['UA-110266862-1', 'ca.qliktive.com']

pages:
  - startpage: index.md
  - Documentation:
    - Home: home.md
    - Getting Started: getting-started.md
    - Downloads: downloads.md
    - Tutorials:
      - Hello Engine: tutorials/hello-engine.md
      - Hello Data: tutorials/hello-data.md
      - Hello Visualization: tutorials/hello-visualization.md
      - Orchestration: tutorials/orchestration.md
      - Authorization: tutorials/authorization.md
      - Data Loading: tutorials/data-loading.md
      - Document Distribution: tutorials/document-distribution.md
      - Scalability:
        - Overview: tutorials/scalability/overview.md
        - Newspaper website: tutorials/scalability/newspaper.md
    - Services:
      - QIX Engine: documentation/services/qix-engine.md
      - License Service: documentation/services/license-service.md
      - Mira: documentation/services/mira.md
    - APIs:
      - Data Connector GRPC: documentation/apis/data-connector-grpc.md
      - QIX Engine:
        - Definitions: documentation/apis/qix-engine-definitions.md
        - Global: documentation/apis/qix-engine-global.md
        - Doc: documentation/apis/qix-engine-doc.md
        - Generic Object: documentation/apis/qix-engine-genericobject.md
        - Generic Bookmark: documentation/apis/qix-engine-genericbookmark.md
        - Generic Derived Field: documentation/apis/qix-engine-genericderivedfields.md
        - Generic Dimension: documentation/apis/qix-engine-genericdimension.md
        - Generic Measure: documentation/apis/qix-engine-genericmeasure.md
        - Generic Variable: documentation/apis/qix-engine-genericvariable.md
        - Field: documentation/apis/qix-engine-field.md
        - Variable: documentation/apis/qix-engine-variable.md
    - Contract: documentation/contract.md
    - Support & Services:
      - Licensing: support-and-services/licensing.md
      - Sales: support-and-services/sales.md
      - Technical Support: support-and-services/tech-support.md
      - Training: support-and-services/training.md
  - Beta: beta.md
