site_name: Qlik Core
site_url: 'https://core.qlik.com'

theme:
  name: 'material'
  logo: 'images/qlik-core-logo-white.svg'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  font:
    text: 'Source Sans Pro'
    code: 'Roboto Mono'
  # 404 page

  static_templates:
    - 404.html

site_description: 'Qlik Core is an analytics development platform built around the 
                   Qlik Associative Engine and Qlik-authored open source libraries.'

extra_css:
  - 'stylesheets/custom-style.css'
  - 'stylesheets/downloads.css'
extra_javascript:
  - 'javascripts/extra.js'
  - 'https://unpkg.com/enigma.js@2.2.1/enigma.min.js'
  - 'javascripts/downloads.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/qlik-oss/core-website'
    - type: 'slack'
      link: 'http://qlikbranch-slack-invite.herokuapp.com/'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ./
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

strict: true
repo_name: 'qlik-oss/core-website'
repo_url: 'https://github.com/qlik-oss/core-website'
edit_uri: edit/master/docs
google_analytics: ['UA-110266862-2', 'auto']

nav:
  - Home: index.md
  - Get Started: get-started.md
  - Downloads: downloads.md
  - Updates:
    - November 2018: updates/2018-11.md
    - October 2018: updates/2018-10.md
  - Licensing: licensing.md
  - EULA: eula.md
  - Use Cases: use-cases.md
  - Tutorials:
    - Hello Engine: tutorials/hello-engine.md
    - Hello Data: tutorials/hello-data.md
    - Hello Visualization: tutorials/hello-visualization.md
    - Orchestration: tutorials/orchestration.md
    - Authorization: tutorials/authorization.md
    - Data Loading:
      - Local Files: tutorials/data-loading/local-files.md
      - Remote Files: tutorials/data-loading/remote-files.md
      - Databases: tutorials/data-loading/databases.md
  - Tooling:
    - Overview: tooling/overview.md
    - corectl: tooling/corectl.md
    - catwalk: tooling/catwalk.md  
  - Services:
    - Mira: services/mira.md
    - Qlik Associative Engine:
      - Introduction: services/qix-engine/introduction.md
      - Access Control: services/qix-engine/access-control.md
      - Document Synchronization: services/qix-engine/doc-synchronization.md
      - Logging: services/qix-engine/logging.md
      - Resource Management: services/qix-engine/resource-management.md
      - QIX API:
        - Introduction: services/qix-engine/apis/qix/introduction.md
        - Definitions: services/qix-engine/apis/qix/definitions.md
        - Global: services/qix-engine/apis/qix/global.md
        - Doc: services/qix-engine/apis/qix/doc.md
        - Generic Object: services/qix-engine/apis/qix/genericobject.md
        - Generic Bookmark: services/qix-engine/apis/qix/genericbookmark.md
        - Generic Dimension: services/qix-engine/apis/qix/genericdimension.md
        - Generic Measure: services/qix-engine/apis/qix/genericmeasure.md
        - Generic Variable: services/qix-engine/apis/qix/genericvariable.md
        - Field: services/qix-engine/apis/qix/field.md
        - Variable: services/qix-engine/apis/qix/variable.md
      - Data Connector API:
        - Introduction: services/qix-engine/apis/data-loading/introduction.md
        - API Specification: services/qix-engine/apis/data-loading/data-connector-api.md
      - Analytical Connector API:
        - Introduction: services/qix-engine/apis/server-side-extension/introduction.md
        - API Specification: services/qix-engine/apis/server-side-extension/analytical-connector-api.md
      - Rest API: services/qix-engine/apis/rest/qlik-associative-engine-api.md
      - Load Script Reference:
        - Introduction: services/qix-engine/script_reference/introduction.md
        - Script syntax:
          - Error variables: services/qix-engine/script_reference/error.md
          - Operators: services/qix-engine/script_reference/operators.md
          - Control statements: services/qix-engine/script_reference/script_control.md
          - Regular statements: services/qix-engine/script_reference/Script_regular_statements.md
          - Prefixes: services/qix-engine/script_reference/script_prefix.md
          - Variables:
            - Overview: services/qix-engine/script_reference/variables.md
            - Number: services/qix-engine/script_reference/number_variables.md
            - Value handling: services/qix-engine/script_reference/value_handling_variables.md
        - Script functions:
          - Aggregation Functions:
            - Basic Aggregation Functions: services/qix-engine/script_reference/basic_aggregation_functions.md
            - Counter Aggregation Functions: services/qix-engine/script_reference/counter_aggregation_functions.md
            - Financial Aggregation Functions: services/qix-engine/script_reference/financial_aggregation_functions.md
            - Statistical Aggregation Functions: services/qix-engine/script_reference/statistical_aggregation_functions.md
            - Statistical Test Functions: services/qix-engine/script_reference/statistical_test_functions.md
            - String Aggregation Functions: services/qix-engine/script_reference/string_aggregation_functions.md
          - Color Functions: services/qix-engine/script_reference/color_functions.md
          - Conditional Functions: services/qix-engine/script_reference/conditional_functions.md
          - Counter Functions: services/qix-engine/script_reference/counter_functions.md
          - Date And Time Functions: services/qix-engine/script_reference/date_and_time_functions.md
          - Exponential And Logarithmic Functions: services/qix-engine/script_reference/exponential_and_logarithmic_functions.md
          - File Functions: services/qix-engine/script_reference/file_functions.md
          - Financial Functions: services/qix-engine/script_reference/financial_functions.md
          - Formatting Functions: services/qix-engine/script_reference/formatting_functions.md
          - General Numeric Functions: services/qix-engine/script_reference/general_numeric_functions.md
          - Geospatial Functions: services/qix-engine/script_reference/geospatial_functions.md
          - Interpretation Functions: services/qix-engine/script_reference/interpretation_functions.md
          - Inter-Record Functions: services/qix-engine/script_reference/inter-record_functions.md
          - Logical Functions: services/qix-engine/script_reference/logical_functions.md
          - Mapping Functions: services/qix-engine/script_reference/mapping_functions.md
          - Mathematical Functions: services/qix-engine/script_reference/mathematical_functions.md
          - NULL Functions: services/qix-engine/script_reference/NULL_functions.md
          - Range Functions: services/qix-engine/script_reference/range_functions.md
          - Statistical Distribution Functions: services/qix-engine/script_reference/statistical_distribution_functions.md
          - String Functions: services/qix-engine/script_reference/string_functions.md
          - System Functions: services/qix-engine/script_reference/system_functions.md
          - Table Functions: services/qix-engine/script_reference/table_functions.md
          - Trigonometric And Hyperbolic Functions: services/qix-engine/script_reference/trigonometric_and_hyperbolic_functions.md
    - License: services/licenses.md
  - Conventions:
    - Introduction: conventions/introduction.md
    - API Strategy: conventions/api-strategy.md
    - Logging: conventions/logging.md
    - Metrics: conventions/metrics.md
  - Third Party Licenses: third-party-licenses.md
  - License Registration: license-registration.md
