site_name: Frontira
theme: material

repo_name: 'qlik-ea/info'
repo_url: 'https://github.com/qlik-ea/info'

pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - Downloads: downloads.md
  - Tutorials:
    - Hello Engine: tutorials/hello-engine.md
    - Hello Data: tutorials/hello-data.md
    - Hello Visualization: tutorials/hello-visualization.md
    - Web Platform: tutorials/web-platform.md
    - Setting up the Core Services: tutorials/core.md
    - Authorization: tutorials/authorization.md
    - Data Loading: tutorials/data-loading.md
    - Document Distribution: tutorials/document-distribution.md
    - Monitoring and Scaling: tutorials/monitoring-and-scaling.md
  - Documentation:
    - Services:
      - QIX Engine: documentation/services/qix-engine.md
      - License Service: documentation/services/license-service.md
      - Mira: documentation/services/mira.md
    - Contract: documentation/contract.md
    - APIs: documentation/apis.md
    - Data Connector GRPC API: documentation/data-connector-grpc-api.md
  - Use Cases:
    - Custom Analytics UI: use-cases/use-case-custom-analytics/README.md
  - Support & Services:
    - Licensing: support-and-services/licensing.md
    - Sales: support-and-services/sales.md
    - Technical Support: support-and-services/tech-support.md
    - Training: support-and-services/training.md
  - Pricing: pricing.md
