version: 2
jobs:
  build:
    machine: true
    working_directory: ~/info
    steps:
      - checkout
      - run:
          name: Lint the documentation
          command: ./lint.sh
      - run:
          name: Build the site
          command: ./build.sh
      - store_artifacts:
          path: ./site
      - run:
          name: Deploy the site
          command: |
            export TARGET_USER=ubuntu
            export TARGET_HOST=ec2-54-246-193-78.eu-west-1.compute.amazonaws.com
            export BUILD_NUMBER=$CIRCLE_BUILD_NUM
            export BRANCH_NAME=$CIRCLE_BRANCH
            .circleci/deploy.sh
